name: Run Script on every commit

on:
  push:
    branches:
      - main   

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Run and capture the xconf vulnerabilities
        run: |
           echo "Hello World of GitHub Actions"
