name: Hello World Workflow

on:
  workflow_dispatch: 

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run
        run: |
          echo "Hello World code of GitHub Actions"
    
         
