name: Run Vulnerability scan on Push

on:
  push:
    branches:
    - main  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # pulls your repo files into the runner

      - name: Run script
        run: |
          chmod +x .github/workflows/capture_vulnerabilities_xconf.sh
          source .github/workflows/capture_vulnerabilities_xconf.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name:  xconf_vulnerability_reports
          path:  ~/xconf_vulnerability_reports

    
         
