name: Run Vulnerability scan on Push

on:
  push:
    branches:
    - main  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # pulls your repo files into the runner

      - name: Run script
        run: |
          chmod +x .github/workflows/capture_snyk_audit.sh
          source .github/workflows/capture_snyk_audit.sh
          env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name:  xconfui_snyk_audit_check
          path: ${{ github.workspace }}/xconf_snyk_vulnerability_reports/capture_snyk_results.txt
